Perfo mission ui
fast-aircraft-design/FAST-OAD pull request #232
Opened 2020-10-12 07:39 UTC by christophe-david

This PR adds the possibility to define the sizing mission from an input file.

2020-11-17 08:24 UTC, ScottDelbecq requested changes
Mécanique compliquée pour utilisation simple :) Top !
Par contre il faut mettre à jour le fichier `CERAS01_baseline.xml` dans le répertoire notebooks car avec le fichier de configuration `oad_process_mission.toml` la MDA ne fonctionne pas et on ne pourra pas mettre d'exemple mission dans le tuto.

2020-11-17 15:58 UTC, christophe-david commented on src/fastoad/base/flight_point.py
> +            42
Effectivement, c'est un reste de la doc avant que je ne crée `DynamicAttributeDict` pour migrer la mécanique dedans.
Mais vu que cette partie va être complètement chamboulée par la PR #243 , on peut peut-être en rester là ?

2020-11-17 16:00 UTC, christophe-david commented on src/fastoad/cmd/resources/fastoad.toml
> +#        out_file = "./flight_points.csv"
Tu as dû remarquer que le prix à payer pour ce changement est que FAST-OAD attends un path dès lors que le nom de l'option se termine "comme il faut". Pas génial, mais je n'ai pas trouvé mieux.
Et effectivement, c'était dommage de devoir se coltiner un chemin complet.

2020-11-17 16:04 UTC, christophe-david commented on src/fastoad/models/performances/mission/mission_definition/tests/data/mission.yml
> +      CD: 0., 0.03, 0.12
Right. Voir la classe fastoad.models.performances.mission.polar.Polar

2020-11-17 16:10 UTC, ScottDelbecq commented on src/fastoad/base/flight_point.py
> +            42
ça me va ! Je n'en connaissais pas l'existence ce matin :)

2020-11-17 16:15 UTC, christophe-david commented on src/fastoad/base/dict.py
>  #  This file is part of FAST : A framework for rapid Overall Aircraft Design
Bien vu. Correction générale à venir dans une PR dédiée, histoire de ne pas "bruiter" celle-ci...

2020-11-18 13:38 UTC, christophe-david commented
> Mécanique compliquée pour utilisation simple :) Top !
Je ne suis pas étonné par le qualificatif "compliqué". Le problème à résoudre n'était de toute façon pas simple. Mais d'un point de vue maintenabilité, cela te semble-t-il acceptable comme complexité ? En gros, penses-tu que tu pourrais assurer la maintenance de cette partie si demain, je me faisais aspirer par un vortex interdimensionnel ? :)

> Par contre il faut mettre à jour le fichier `CERAS01_baseline.xml` dans le répertoire notebooks car avec le fichier de configuration `oad_process_mission.toml` la MDA ne fonctionne pas et on ne pourra pas mettre d'exemple mission dans le tuto.
Fait dans af9658e00659a7ee925b2e71a53ec0cd72e2b8ad
Le calcul aboutit maintenant. Il reste un souci sur le calcul de déroutement, mais je m'en suis rendu compte en travaillant sur la PR #243 et la correction y est faite.

2020-11-18 16:14 UTC, ScottDelbecq approved these changes

2020-11-18 16:14 UTC, merged