Atmosphere cas added
fast-aircraft-design/FAST-OAD pull request #371
Opened 2021-07-26 08:23 UTC by areysset

The method calculating CAS in atmosphere class has been added.
The corresponding test has also been added.

2021-07-27 07:36 UTC, christophe-david requested changes
Thank you for this proposal.

As you will see, I have some comments, but the most important one is that you implemented a conversion that is valid only for subsonic flows.

Indeed, our current applications are at most transonic.
Indeed, the TAS<->CAS conversion in supersonic flows is [trickier](https://en.wikipedia.org/wiki/Calibrated_airspeed) 
And indeed, handling these two cases while taking into account the possible array-shape of inputs needs attention.

But the Atmosphere class should aim at being a solid and "universal" basis, and personally, knowing that EAS is close enough to CAS for the subsonic domain (considering the needed accuracy for conceptual studies), I prefer having no CAS computation than having a half-baked one.

Yet, I do not doubt that CAS computation is needed to have a complete Atmosphere class, but this computation should be reliable even above Mach 1.0.

2021-07-27 07:36 UTC, christophe-david commented on src/fastoad/model_base/atmosphere.py
> +                mach = (2.0 / (gamma - 1.0) * (sigma_0 ** ((gamma - 1.0) / gamma) - 1.0)) ** 0.5
Here your formula explicitly uses gamma, but in the formula above, you use `3.5`, which is &#947;/(&#947;-1). For sake of consistency, the `gamma` variable should be used everywhere, or nowhere. And for sake of efficiency, I think that nowhere is the best choice.

Therefore, I suggest:
```suggestion
                mach = (5.0 * (sigma_0 ** (1.0 / 3.5) - 1.0)) ** 0.5
```

2021-07-27 13:58 UTC, areysset commented
The formula has been changed to take into account [supersonic flight](https://en.wikipedia.org/wiki/Equivalent_airspeed)!

2021-07-27 15:33 UTC, christophe-david commented
> The formula has been changed to take into account [supersonic flight](https://en.wikipedia.org/wiki/Equivalent_airspeed)!

Ok, so it looks like my suggestion was a bad one, since results get further from reference values.
We will have to use the hard way, then...

2021-07-29 13:55 UTC, areysset commented
The new formulas taken from [Ref](https://rosap.ntl.bts.gov/view/dot/8909) highligh lower relative errors to reference results.
Also, we are not sure at which point reference results from [URL](http://www.aerospaceweb.org/design/scripts/atmosphere/) are 100% correct (error = 0%)?

2021-07-29 14:40 UTC, christophe-david commented
Another point: given your last modifications, I think you may have not read all my initial comments about gamma, and the mach-related code lines, did you ?
I can also add another point I should have spotted earlier: you can replace all your occurences of `current_level` by `self`.

2021-07-29 14:51 UTC, areysset commented
> Another point: given your last modifications, I think you may have not read all my initial comments about gamma, and the mach-related code lines, did you ?
> I can also add another point I should have spotted earlier: you can replace all your occurences of `current_level` by `self`.

I did miss the comment about gamma, sorry for that. I'll remove it definitly.
I'm gonna replace current_level then...

2022-02-21 10:36 UTC, christophe-david commented
Version 0.2.0 of [StdAtm](https://pypi.org/project/stdatm/) proposes a computation of calibrated airspeed, valid at subsonic and supersonic speeds, (and also dynamic and impact pressures).

2022-02-21 10:36 UTC, closed without merging