Memory fix
fast-aircraft-design/FAST-OAD pull request #443
Opened 2022-06-09 15:52 UTC by christophe-david

OpenMDAO objects were persisting in RAM after setup or run operations.
This could be a problem when running multiple computations in the same Python session: memory consumption was continuously raising, and computation time was increasing.

This was due to iPOPO instantiating OpenMDAO components, but never releasing them, since we did not ask to.

This PR solves this problem in a somehow rough way, but it apparently works fine.

2022-06-14 07:40 UTC, ScottDelbecq requested changes
Thank you for the PR!

I have a single comment that discusses whether memory cleaning is necessary after running a model. Nevertheless, it can be seen as us being cautious without impacting performance.

Also, it seems that the new memory test is not integrated in the CI yet.

2022-06-14 07:40 UTC, ScottDelbecq commented on src/fastoad/openmdao/problem.py
> +        BundleLoader().clean_memory()
If I comment the two lines (and leave `.clean_memory()` only after the `.setup()`) your test passes. 
If I change your test with a single setup and multiple `run_model`:

```python
def run_problem():
    configurator = oad.FASTOADProblemConfigurator(pth.join(DATA_FOLDER_PATH, "oad_process.yml"))
    configurator.input_file_path = pth.join(RESULTS_FOLDER_PATH, "inputs.xml")
    configurator.output_file_path = pth.join(RESULTS_FOLDER_PATH, "outputs.xml")
    print_memory_state("After reading configuration file")

    ref_inputs = pth.join(DATA_FOLDER_PATH, "CeRAS01.xml")
    configurator.write_needed_inputs(ref_inputs)
    print_memory_state("After writing input file")

    problem = configurator.get_problem(read_inputs=True)
    print_memory_state("After building problem")

    problem.setup()
    print_memory_state("After problem setup")

    count = 100
    for i in range(count):
        print(f"RUN {i+1}/{count}")
        problem.run_model()

    print_memory_state("After problem run")

    problem.write_outputs()
```

The test still passes. Therefore, I wonder if it is necessary to clean the memory after a `run_model`or `run_driver`. Or our tests are not stringent enough? What do you think?

2022-06-15 13:51 UTC, christophe-david commented
> Also, it seems that the new memory test is not integrated in the CI yet.

Done in cfcb69f805ff52fa3b01448f31b9a4b945c2c0a0

2022-06-15 14:38 UTC, ScottDelbecq approved these changes

2022-06-15 14:39 UTC, merged