Added warning for nan values when generating inputs
fast-aircraft-design/FAST-OAD pull request #468
Opened 2022-11-17 10:27 UTC by ScottDelbecq

This PR closes #278 by adding a warning when NaN values are encountered in the source file of `generate_inputs`.

2022-11-18 09:19 UTC, christophe-david requested changes
Thank you for this work, and for having tried the caplog fixture.

Some issues to fix and it will be right.

2022-11-18 10:40 UTC, ScottDelbecq commented on src/fastoad/io/configuration/configuration.py
> +                if np.all(np.isnan(var.value)):
I think there is very little chances that this occurs but you are right!
Corrected in 8912826.
I also corrected for the verification during computation in 278e90a.

2022-11-18 10:41 UTC, ScottDelbecq commented on src/fastoad/io/configuration/configuration.py
> +                _LOGGER.warning(msg)
Ok. Changed in c2d6d3c.

2022-11-18 10:42 UTC, ScottDelbecq commented on src/fastoad/io/configuration/tests/test_configuration.py
> +            assert record.levelname == "WARNING"
Changed in ee45d1e.

2022-11-18 10:43 UTC, ScottDelbecq commented on src/fastoad/io/configuration/tests/data/ref_inputs_with_nan.xml
> +    <bar>42</bar><!-- This totally unused variable is expected to be transferred in output file -->
Corrected in 37b3aac.

2022-11-21 09:43 UTC, christophe-david commented on src/fastoad/io/configuration/configuration.py
> +                if np.all(np.isnan(var.value)):
Nice. Thank you.

2022-11-21 09:44 UTC, christophe-david approved these changes
All right !

2022-11-21 09:44 UTC, merged