Added only takeoff segments and polar.
fast-aircraft-design/FAST-OAD pull request #481
Opened 2023-02-14 09:27 UTC by esnguyenvan

This is a separate pull request to include only dedicated takeoff segments and polar modifier. The changes to mission builder will be added separately.

2023-02-14 15:51 UTC, christophe-david requested changes
Thank you for this contribution.

I am globally Ok with the content, but the form should be enhanced.
In particular, you will see that I made several remarks about consistency. That may look futile, but it is not, as stated in this quote from PEP 8:
> [A Foolish Consistency is the Hobgoblin of Little Minds](https://peps.python.org/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)
> 
> One of Guido’s key insights is that code is read much more often than it is written. The guidelines provided here are intended to improve the readability of code and make it consistent across the wide spectrum of Python code. As [PEP 20](https://peps.python.org/pep-0020) says, “Readability counts”.
> 
> A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.

My remarks about consistency are especially justified by the 2 last sentences.

I will also mention that I am not too happy with the implementation of takeoff segments because it overrides several methods in a way that repeats more or less some existing code.
But I acknowledge you had little choice for that: it shows the base classes should be thought differently.
So, we will keep things this way for this PR, and I will do the required modifications in the next PR.

Thank you again, and please come back to me for any question.

2023-02-14 15:51 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/base.py
> +    start: FlightPoint = field(default=MANDATORY_FIELD, init=False)
As you can see, `_attribute_units` is not a dataclass field, but a class attribute (and private). Please keep it in last position.

2023-02-14 15:51 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/ground_speed_change.py
> +
Here is the first of the 2 modifications that would use the suggested change in [`GroundEffectRaymer`](https://github.com/fast-aircraft-design/FAST-OAD/pull/481/files#diff-86d2c880fe0a8ceb8ce6e2663eba2fefec24a08ab5a207d69cdd3b25deaba50e).
```suggestion
    def compute_from_start_to_target(self, start: FlightPoint, target: FlightPoint) -> pd.DataFrame:
        self.polar_modifier.ground_altitude = start.altitude
        return super().compute_from_start_to_target(start, target)

```

2023-02-14 15:51 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/ground_speed_change.py
> +            modified_polar = self.polar_modifier.modify_polar(self.polar, flight_point_copy)
And the second modification that would use the suggested change in [GroundEffectRaymer](https://github.com/fast-aircraft-design/FAST-OAD/pull/481/files#diff-86d2c880fe0a8ceb8ce6e2663eba2fefec24a08ab5a207d69cdd3b25deaba50e).
```suggestion
            modified_polar = self.polar_modifier.modify_polar(self.polar, flight_point)
```

2023-02-14 15:51 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/ground_speed_change.py
> +        It is interesting to set equivalent speed or Mach target for non isa conditions
Strange for a dosctring...

2023-02-15 08:49 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +    assert_allclose(last_point.ground_distance, 302.97, rtol=1e-3)
It would be good to also test the final value of alpha.

2023-02-15 08:51 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +    assert_allclose(last_point.ground_distance, 200.64, rtol=1e-3)
Wouldn't it be good to also test the final value of alpha?

2023-02-15 09:06 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +    # initialisation then change instance attributes
Most comments in this file do not apply to current code.

2023-02-15 09:09 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +        target=FlightPoint(altitude=12.0),
```suggestion
        target=FlightPoint(),
```

2023-02-15 09:22 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +    # Note: reference values are obtained by running the process with 0.01s as time step
Is that true? (just wondering if it is not a simple copy/paste artifact)

2023-02-15 09:27 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +        print(df)
Useless.

2023-02-15 09:27 UTC, christophe-david commented on src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
> +    )  # Test with dict
Does not apply.

2023-02-16 10:07 UTC, esnguyenvan commented
Hello,
Thanks for the comments, I tried to address everything and proposed some additional changes in the last commit. Please let me know if I forgot something or if new changes have to be corrected

2023-02-17 14:27 UTC, christophe-david requested changes
Thank you for the modifications.

Some small details left and that should be ok.

2023-02-17 16:45 UTC, esnguyenvan commented
Now it should be fixed with rebase from master

2023-02-28 09:33 UTC, christophe-david approved these changes
👍

2023-02-28 09:34 UTC, merged