Enhanced documentation for mission segment parameters
fast-aircraft-design/FAST-OAD pull request #582
Opened 2024-12-10 07:17 UTC by christophe-david

This PR allows to better link mission segments and their parameters in the segment documentation.

Preview here: https://fast-oad.readthedocs.io/en/mission-doc-update/documentation/mission_module/mission_file/segments.html

2024-12-17 08:54 UTC, enricostragiotti requested changes
Thank you very much for this definitely needed function! While I'm definitely no expert in Sphinx, I found the logic behind it very clear and concise. 

In this short review I focused only on some little inconsistency i found in the documentation (some are not even directly concerned by this PR, but I find pretty important to fix them).

Thank you again for your PR :)

2024-12-17 08:54 UTC, enricostragiotti commented on docs/directives/segment_attributes.py
> +    has_content = True
Is this variable used?

2024-12-17 08:54 UTC, enricostragiotti commented on docs/documentation/mission_module/mission_file/segments.rst
> +The segment target is a special parameter, detailed in :ref:`further section<segment-parameter-target>`.
so is it a parameter or a segment? For what I understand it cannot be called on his own but only as a parameter of another segment no?

2025-01-22 09:24 UTC, christophe-david commented on docs/directives/segment_attributes.py
> +    has_content = True
It is mandatory in order to have `self.content` populated (see https://www.sphinx-doc.org/en/master/extdev/markupapi.html#docutils.parsers.rst.Directive.has_content)
e.g. .. `start` is the "content" in `list-attributes-for:: start`
I have to say I don't really understand the difference between `Directive.content` and `Directive.arguments`. But her, I use `content`.

2025-01-22 09:41 UTC, christophe-david commented on docs/directives/segment_attributes.py
> +    The list will be references to paragraphs, provided they are tagged like
That's not what I meant, but I admit the sentence is not so clear. I try to do better in e0d3bab23c73974b44407e784b9245621ad62357

2025-01-22 09:42 UTC, christophe-david commented on docs/directives/segment_attributes.py
> +    The list will be references to paragraphs, provided they are tagged like
Same as above, see e0d3bab23c73974b44407e784b9245621ad62357

2025-01-22 09:42 UTC, christophe-david commented on docs/conf.py
>  copyright = "2021, ONERA & ISAE-SUPAERO"
Done in dc3614fbd29982a14b8f650324d1d0a8084f8018

2025-01-22 09:56 UTC, christophe-david commented on docs/documentation/mission_module/mission_file/segments.rst
>  Segment target
I don't understand the first part of your comment. Target is now referenced as a parameter (and then identified by the `list-attributes-for` directive).
About putting target in the special segment parameters, yes, it makes sense.

2025-01-22 09:57 UTC, christophe-david commented on docs/directives/segment_attributes.py
> +    # Retrieving the ènv.target_data populated in the directives.
Done in dc3614fbd29982a14b8f650324d1d0a8084f8018.

2025-01-22 09:57 UTC, christophe-david commented on docs/conf.py
> +# For custom CSS styles (expected in _static/ folder )
Done in dc3614fbd29982a14b8f650324d1d0a8084f8018.

2025-01-22 09:57 UTC, christophe-david commented on docs/conf.py
> +environ["SPHINX_APIDOC_OPTIONS"] = "m∂embers,undoc-members,inherited-members,show-inheritance"
Fixed in dc3614fbd29982a14b8f650324d1d0a8084f8018.

2025-01-22 09:59 UTC, christophe-david commented on docs/_static/custom_admonitions.css
> +*/
Yes. I played a bit with those, but finally decided to not change them. I thought letting them as comments would help future contributors if they want to explore these settings :)

2025-01-22 10:05 UTC, christophe-david commented on docs/documentation/mission_module/mission_file/segments.rst
> +The segment target is a special parameter, detailed in :ref:`further section<segment-parameter-target>`.
I don't understand your confusion.
It is a parameter (well, a segment attribute), it is described as a parameter, you understand it as a parameter, and it is (now) tagged correctly as a parameter. Where is it implied it could be a segment?

2025-01-22 13:36 UTC, christophe-david commented on docs/documentation/mission_module/mission_file/segments.rst
> +.. list-segments-for:: engine_setting
As discussed, the side effect of this PR is to highlight that this segment should be documented 😅

2025-01-22 14:03 UTC, christophe-david commented on docs/directives/segment_attributes.py
> +        if target_exists:
Agreed, but there is a need to understand how `nodes.table` would work in docutils API, with very few documentation...

To be continued...

2025-01-23 09:36 UTC, enricostragiotti commented on docs/documentation/mission_module/mission_file/segments.rst
> +The segment target is a special parameter, detailed in :ref:`further section<segment-parameter-target>`.
Sorry, my bad. At the time of the review I didn’t understand exactly what you was willing to tell. But now I understand and all is good for me :)

2025-01-23 09:37 UTC, enricostragiotti commented on docs/documentation/mission_module/mission_file/segments.rst
> +.. list-segments-for:: engine_setting
reported in #592

2025-01-23 09:40 UTC, enricostragiotti commented
All good for me ! Thanks for the work done @christophe-david !

2025-01-23 09:42 UTC, merged