Add DOE generation atom function
fast-aircraft-design/FAST-OAD pull request #583
Opened 2024-12-13 16:10 UTC by enricostragiotti

In this PR we start the work in building DOE capability in FAST-OAD (#576). here it is my proposition for the atom function (with unit tests) that generates the sampling and produces outputs compatible with CalcRunner. This is done by introducing:

1. Introduction of DOEVariable:
    Represents individual variables used in DOE with customizable bounds, reference values, and binding capabilities.
    Provides error handling for invalid bounds and dynamically adjusts bounds based on reference values.

2. Addition of DOEConfig:
    Manages the configuration and generation of sampling points using SMT
    Supports binding of variables, random seeding for reproducibility, and multilevel sampling using nested LHS.
    Exports generated DOE data into CSV files with options for pseudo-variable names.
    Produces well-formatted outputs compatible with the CalcRunner class in FAST-OAD

2024-12-18 21:16 UTC, christophe-david reviewed
I think it's better to do this review in several steps. Here is the first one.

Additionally to comments in code, I would point out that names like lower_bound, upper_bound, variable_id or name_alias look more "english" to me (I may be wrong, though)

2024-12-18 21:16 UTC, christophe-david commented on src/fastoad/cmd/doe.py
> +            self.bound_upper = self.bind_variable_to.bound_upper
Do you really want to bind bounds? I thought you would want to bind values.

2024-12-18 21:16 UTC, christophe-david commented on src/fastoad/cmd/doe.py
> +            self.id_variable = (
For readability, please declare all instance attributes in the data class header. Non-init attributes can be declared using [field](https://docs.python.org/3/library/dataclasses.html#dataclasses.field).

2024-12-18 21:16 UTC, christophe-david commented on src/fastoad/cmd/doe.py
> +        # Exctarct bounds taking into account binding
typo

2025-02-03 15:01 UTC, florentLutz requested changes
Thanks for the PR and the very nice way of coding. A fe questions to understand better how this isgoind to work and some remarks as well.
A generic remark would be the lack of documentation if these are meant to be used by the user. Or an article in the wiki if this is meant to be used by developers

2025-02-04 11:35 UTC, enricostragiotti commented on pyproject.toml
> +smt = "^2.9.0"
pyDOE3 is actually needed by SMT, in theory we could delete the pyDOE3 dependency. Btw pyDOE3 is not actively developed I think, it is only in bugfix mode. i open an issue and will migrate to SMT for the payload range calculation (where pydoe3 is used). So we can safely delete the explicit need for it

2025-02-04 11:40 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +    :param name: The name of the FAST-OAD DOE variable.
Yes it is true, thanks. We are talking about the openmdao fast variable. I will modify it to make it clearer

2025-02-04 11:44 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +                             the same dimension and same values.
It solves one little problem that is however possible to encouner when creating DOEs, e.g., the tsfc evaluation is parametred using two different k parameters in FAST, respectively the k_cr and k_sl, to finetune the tsfc at cruise and at sea level. Now imagine that you want to modify both at the same time (because it would be not very logical to do using different values (and dimensions of the DOE)). That's what variable binding is doing. we create one dimension that is used for multiple variables at the same time, so that in the doe the two are modified and they share the same value.

2025-02-04 11:45 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +    )  # https://florimond.dev/en/posts/2018/10/reconciling-dataclasses-and-properties-in-python
yes! I think I did it no?

2025-02-04 13:50 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +    _id_counter: ClassVar[itertools.count] = itertools.count()
It is just an internal and unique id used to quickly treat variable binding (see https://github.com/fast-aircraft-design/FAST-OAD/blob/9b8fbda4b833e97d310322c03c84a72c402648db/src/fastoad/cmd/doe.py#L218). An alternative would have been to use a hash function maybe?

2025-02-04 15:35 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +            return self.bind_variable_to.lower_bound
No, because the `__post_init__` method runs only once when the class is instantiated. If you assign `varB` in `__post_init__`, it will take the current value of `varA` at that moment, but it won’t update if `varA` changes later.  

On the other hand, if you use a getter for `varB`, the code inside it will run every time `varB` is accessed. This ensures that `varB` always reflects the current value of `varA`, even if `varA` is modified after the object is created.

2025-02-04 16:02 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +                )
This is just in the case as a user you set a variable with binding AND explicit bounds, that makes no sense. If two variables are binded the bounds are shared, you cannot assign any other values. So they will be ignored with a warning

2025-02-04 16:17 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +                )
Nevermind, I now better understand your comment. You are absolute right. I will change it. i will leave only the warning in the setter of the properties. but in order to do I need for the bind_variable_to parameter to be higher in the list of the inputs of the dataclass. I I don't do it there is the risk to call the setter of lower and upper bounds without the class having read the `bind_variable_to`

2025-02-04 16:22 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        self.variables_binding = [var.variable_id for var in self.variables]
Bad naming, my bad!

2025-02-04 16:24 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        self.var_names_pseudo = [var.name_alias for var in self.variables]
it's a pseudo that you can give to variables to have that in the output instead of the very long and sometimes confusing openMDAO varriable name. Like "Sizing BF [kg]" instead of "data:mission:sizing:needed_block_fuel"

2025-02-04 16:27 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        self.bounds = []
I construct the bounds as a list, but SMT want a numpy array. would you prefer if I use directly a np array and np.append?

2025-02-04 16:35 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        return samp.LHS(criterion="ese", xlimits=self.bounds, random_state=self.seed_value)
https://en.wikipedia.org/wiki/Latin_hypercube_sampling

It is the most used sampling method used for creating a DOE. 
the nested LHS is an algorithm that permit to create first a LHS sampling (level0) and then add another level (usually with more points), that is still well spaced in the sense of the LHS. It is very useful to create multi-fidelity surrogate models. More info here: https://smt.readthedocs.io/en/latest/_src_docs/applications/mfk.html

2025-02-04 16:36 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
Because here is where Christophe put calcrunner. Do you have suggestion for a different location?

2025-02-04 16:44 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        doe_points_dict = self.doe_points_df.to_dict(orient="records")
That's true, just an habit :)

2025-02-04 16:47 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        ]
Not here directly, It is gonna be used in the integration phase.. I really don't know what to do with these functions. would you prefer to have them written only with the integration PRs? Otherwise in this specific case we can call it in the sample doe method. and we can thus get rid of the user error. What do you think?

2025-02-04 17:17 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    assert var2.variable_id != var1.variable_id
I just want to check that if two vars aren't binded, they have different id, no?

2025-02-04 17:18 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    assert config.bounds.shape == (2, 2)  # 3 variables, but one is binded
Yes because even if there are 3 variables the dimension of the LHS is 2

2025-02-04 17:20 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    np.testing.assert_array_equal(config.bounds[0], np.asarray([0, 10]))  # Bounds from var1
bounds is a list of np ndarray

2025-02-04 17:21 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    assert all(isinstance(item, VariableList) for item in doe_points)
yes why not, I'll add it!

2025-02-10 09:13 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +    """Represents a Design of Experiments (DOE) variable defined by its unique `variable_id`.
But wouldn't it be weird to have a DOEVariable.doe_variable_id?
maybe the best is just to use id?

2025-02-10 10:58 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        self.var_names_pseudo = [var.name_alias for var in self.variables]
in reality they are immutable and should not be initialized in the constructor, as there is the risk to have them not synchronized if the variable list is modified in the runtime. i'll set them as properties

2025-02-10 11:02 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +                    doe_points_upd = point_list[:, self.variables_binding]
updated, do you find it as bad naming?

2025-02-10 11:03 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +        )
I'll split it

2025-02-10 15:40 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    assert all(isinstance(item, VariableList) for item in doe_points)
Yes to do that I ended writing an additional function that is used to create a list of VariableList starting from an input csv and a name_mapper

2025-02-10 15:53 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    doe_points = config.sample_doe(sample_count=5)
At the end I think the best idea is just to rename DOEConfing in DOESampling no?

2025-02-10 16:52 UTC, enricostragiotti commented
> Thanks for the PR and the very nice way of coding. A fe questions to understand better how this isgoind to work and some remarks as well. A generic remark would be the lack of documentation if these are meant to be used by the user. Or an article in the wiki if this is meant to be used by developers

Thank you very much @florentLutz for the patience in reviewing my code and thank you very much for the much appreciated comments! I tried my best to take into account all of them.

2025-02-13 15:35 UTC, florentLutz commented on pyproject.toml
> +smt = "^2.9.0"
So you are waiting for the migration of the payload range to safely delete it ?

2025-02-13 15:39 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +"""Tools for generating and postprocess Design of Experiments (DOEs) in FAST-OAD."""
I noticed you now changed it to 
```python
"""Python module containing the tools for generating and postprocessing Design of
Experiments (DOEs) in FAST-OAD."""
```
But to be honest, if the docstring must span multiple line I prefer it like this
```python
"""
Python module containing the tools for generating and postprocessing Design of Experiments (DOEs) in
FAST-OAD.
"""
```
Not very important though

2025-02-13 15:41 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +    """Represents a Design of Experiments (DOE) variable defined by its unique `variable_id`.
True ! I like that compromise

2025-02-13 15:44 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +                             the same dimension and same values.
Thanks for the explanation ! I think that example is very telling and would need to be somewhere like a documentation 😉

2025-02-13 15:44 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +    )  # https://florimond.dev/en/posts/2018/10/reconciling-dataclasses-and-properties-in-python
Yes you did, that was not the goal of my remark 😅 I just wanted to highlight that it's very immportant in that case :)

2025-02-13 15:50 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +            return self.bind_variable_to.lower_bound
Thanks for the explanation

2025-02-13 15:55 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +                )
Whichever is simpler, I realize I was a bit overzealous on that comment 😅

2025-02-13 15:59 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        self.var_names_pseudo = [var.name_alias for var in self.variables]
If you want them to be immutable, can't you use tuple instead of list ?

2025-02-13 16:07 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        self.bounds = []
It's clearer now, it can remain like this

2025-02-13 16:08 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        return samp.LHS(criterion="ese", xlimits=self.bounds, random_state=self.seed_value)
Osrry I wasn't clear enough I was talking about the "ese" criterion

2025-02-13 16:11 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +                    doe_points_upd = point_list[:, self.variables_binding]
Is updated not short enough ? I don't mind it but maybe just write it in the comment before (replace Rearrange with Update)

2025-02-13 16:12 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        doe_points_dict = self.doe_points_df.to_dict(orient="records")
Nope, i was just curious

2025-02-13 16:15 UTC, florentLutz commented on src/fastoad/cmd/tests/test_doe.py
> +    assert var2.variable_id != var1.variable_id
Then the name of the test function should be different, no ?

2025-02-13 16:22 UTC, florentLutz commented on src/fastoad/cmd/tests/test_doe.py
> +    np.testing.assert_array_equal(config.bounds[0], np.asarray([0, 10]))  # Bounds from var1
So bounds[0] is an array right ? And assert works great on array if I'm not mistaken

2025-02-14 07:54 UTC, florentLutz reviewed
I have a few more question but it's more about understanding than questionning your work 😄

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +    """Represents a Design of Experiments (DOE) variable defined by its unique `id`.
Same overly zealous remark as for the module docstring: I prefered if the start of the docstring is not on the same line as the `"""` if you have multiple lines ^^

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +class DOESampling:
As mentionned in another comment, I'm not againt the name DOEConfig

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        return [var.name for var in self.variables]
Again, me being picky about something I didn't think about the first rounf of review and which ultimately might not lead to a lot of speedups but this regenrates the list each time we want to access var_names. Will it be worth thinking about something like this:
```python
 @property
    def var_names(self):  # noqa: F811
        """List of the names of the DOEVariables."""
        if not self._var_names:
               self._var_names =  [var.name for var in self.variables]
        return self._var_names
```
Though this will only be better if var_names is accessed more than once and is not likely to change

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +                if var.name not in seen_names:
Again, I'm just realizing it now but a variable can have a different id (so enter the first if) and have a different name ? Or are you just doing that to seggregate the case where you have a bound variable and twice the same variable ? In the latter case, wouldn't it be more efficient to switch the two ifs ?

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        ]
Actually, I think I changed my mind, you use _write_doe_inputs_ here, after the sampling is performed so it never should be an issue. Except in the case where someone uses a private function, which is "not our problem" 😛

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        doe_points_df.insert(0, "ID", range(len(doe_points_df)))  # Create ID column
When the ID doesn't exist you create them with a range but what happens if you have another DOEConfig with the same variables and different ID's ? Is that a realistic case or am I just going too far ?

2025-02-14 07:54 UTC, florentLutz commented on src/fastoad/cmd/tests/test_doe.py
> +RESULTS_FOLDER_PATH = Path(__file__).parent / "results" / Path(__file__).stem
So the result folder path is `...\results\test_doe` ? Was `...\results` not enough ?

2025-02-21 14:06 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        return [var.name for var in self.variables]
mmm I don't thik so, because doing that way if self.variables changes, var_names would not change.

2025-02-21 14:08 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        return samp.LHS(criterion="ese", xlimits=self.bounds, random_state=self.seed_value)
Ah sorry! It is a special LHS implementation by the authors of SMT https://smt.readthedocs.io/en/latest/_src_docs/sampling_methods/lhs.html

2025-02-21 14:21 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        if self.sampling_options and self.sampling_options.get("level_count"):
I missed this comment during the last review, sorry. I don't quite understand your question, sorry 🥲

2025-02-21 14:29 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
The fact is that this would break old code using calc runner..

2025-02-21 14:31 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +RESULTS_FOLDER_PATH = Path(__file__).parent / "results" / Path(__file__).stem
no because inside the folder there are also the results of test_cli, test_calc_runner, etc

2025-02-21 14:38 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    np.testing.assert_array_equal(config.bounds[0], np.asarray([0, 10]))  # Bounds from var1
yes but on arrays this is preferred because it gives an error message pointing to where the error is https://stackoverflow.com/questions/3302949/best-way-to-assert-for-numpy-array-equality

2025-02-21 14:42 UTC, enricostragiotti commented on src/fastoad/cmd/tests/test_doe.py
> +    assert np.allclose(written_data.to_numpy(), expected_data.to_numpy(), atol=1e-4, rtol=1e-4)
the idea is that I want to check that what is written and then read is equal to what has been generated in the first place by DOESampling. So I can use the CSV as an input for a DOE (potentially also sharing it with someone else)

2025-02-21 14:48 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +        doe_points_df.insert(0, "ID", range(len(doe_points_df)))  # Create ID column
mmm for me here the idea is that someone have to chose to not give an explicit IDs and so the method creates them or tho set them in the csv file.I never supposed that we could have multiple DOEs in the runtime..

2025-02-21 14:50 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +class DOESampling:
i answer here. In general I wanted to have one single calss for the DOE (so bounds and var names) and the sampling. Do you think is a necessity? also knowing that these classes won't beaccessible directly from the user, the idea is that thy will be set up by the conf file

2025-03-11 12:02 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        if self.sampling_options and self.sampling_options.get("level_count"):
The if statement and indentation levels leave possible a case where `sampling_options["level_count"]` is not None but  `sampling_options["use_level"]` is which would leave you at line 313 with `use_level = None - 1` which throws an error.

2025-03-11 12:03 UTC, florentLutz commented on src/fastoad/cmd/tests/test_doe.py
> +    assert var2.variable_id != var1.variable_id
You removed the test ?

2025-03-11 12:06 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +class DOESampling:
If its transparent by the user then it's not really an issue

2025-03-11 12:07 UTC, florentLutz commented on src/fastoad/cmd/doe.py
> +        return [var.name for var in self.variables]
👍

2025-03-11 12:08 UTC, florentLutz commented on src/fastoad/cmd/tests/test_doe.py
> +RESULTS_FOLDER_PATH = Path(__file__).parent / "results" / Path(__file__).stem
👍

2025-03-11 12:11 UTC, florentLutz reviewed
One last remark but otherwise you can consider this PR approved

2025-03-11 12:11 UTC, florentLutz commented on src/fastoad/cmd/tests/test_doe.py
> +def test_DOE_from_sampled_csv(sample_csv_file):
Since you are preparing for some heavy changes with linting, I suggest to changed that function name (and more specifically the upper case doe) otherwise it wont pass that rule: https://docs.astral.sh/ruff/rules/invalid-function-name/. It think there are other instances in the test file where that would cause an issue. But then again we might want to exclude test file from the inspection

Especially since in a lot of other function name you use lower case ^^'

2025-03-25 13:49 UTC, enricostragiotti commented on src/fastoad/cmd/doe.py
> +                if var.name not in seen_names:
in reality is to check that the user has not put twice the same variable in the definition of the doe

2025-03-25 14:19 UTC, merged