Ruff import sort
fast-aircraft-design/FAST-OAD pull request #587
Opened 2024-12-18 14:56 UTC by enricostragiotti

## Summary of Changes

This functionality can significantly improve code readability and maintainability by enforcing a consistent import order across the codebase.

## Related Issues

Closes #586 

## Checklist

- [x] Have you followed the guidelines in our [Contributing](https://github.com/fast-aircraft-design/FAST-OAD/wiki/Development-environment) wiki?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [x] Do the existing tests pass with your changes?
- [x] Have you commented on hard-to-understand areas of the code?

## Additional Context
It is a well known bug that for the moment there are some caveats that need to be used to make VS code with the official python extension and pre-commit woks together. For that reason a small modification (non breaking) has been made to the pre-commit configuration file.

2025-01-10 15:46 UTC, florentLutz requested changes
A few small remarks and a point I think we should discuss 😄

2025-01-10 15:46 UTC, florentLutz commented on .pre-commit-config.yaml
> -        entry: nbstripout
Is is it needed to add the `poetry run` ?

2025-01-10 15:46 UTC, florentLutz commented on pyproject.toml
> +relative-imports-order = "closest-to-furthest"
Any other sorting rules to be aware ?
Also, is there a real advantage to combining import ? Won't it impact readability ?

2025-01-10 15:46 UTC, florentLutz commented on src/fastoad/api.py
I think it'd be worth discussing the removal of all those `# noinspection PyUnresolvedReferences`. True it doesn't change anything for ruff but with that removal PyCharm (which I know you don't use) now treat all of those as unused imports. It's really a matter of comfort

2025-01-10 15:46 UTC, florentLutz commented on src/fastoad/notebooks/02_From_Python_to_FAST-OAD/02_pure_Python.ipynb
> -    "\n",
I'm really curious as to why ruff decided to remove that line return

2025-01-14 10:28 UTC, florentLutz commented on pyproject.toml
> +select = ["E4", "E7", "E9", "F", "I"]
This makes me wonder if a line in the github workflow yaml file should be added to check that all imports have been sorted properly (in case someone doesn't uses precommit for example)

2025-01-20 16:13 UTC, enricostragiotti commented on .pre-commit-config.yaml
> -        entry: nbstripout
As already explained this is due to a small bug known in the python vscode extension that has not been yet fixed (https://github.com/microsoft/vscode-python/issues/10165).
doing poetry run, we are sure that we run the command in the env installed by poetry

2025-01-20 16:25 UTC, enricostragiotti commented on src/fastoad/api.py
Have a look here. Could you test if you can setup PyCharm to do format and import sort on save? If yes, do the errors still come out?

https://docs.astral.sh/ruff/editors/setup/#pycharm

2025-01-20 16:42 UTC, enricostragiotti commented on src/fastoad/notebooks/02_From_Python_to_FAST-OAD/02_pure_Python.ipynb
> -    "\n",
don't know exactly for this specific case, but I tried to revert the changes and an error popped up..

2025-01-20 16:46 UTC, enricostragiotti commented on pyproject.toml
> +select = ["E4", "E7", "E9", "F", "I"]
this is already done

```
name: Check with Ruff
run: |
     poetry run ruff check .           # Check coding rules
     poetry run ruff format --check .  # Check format
shell: bash
```

2025-01-20 16:48 UTC, enricostragiotti commented on pyproject.toml
> +relative-imports-order = "closest-to-furthest"
Oups, it was just a test, I forgot to erase that line. Thanks!

2025-01-21 07:43 UTC, florentLutz commented on pyproject.toml
> +select = ["E4", "E7", "E9", "F", "I"]
Thanks for adding the comment in the .yml file ^^'

2025-01-21 07:51 UTC, florentLutz commented on src/fastoad/api.py
I've installed the ruff plugin but it's still throwing warnings about unused imports. So I still think we should keep those `# noinspection PyUnresolvedReferences`. Besides, just like we don't want to impose the use of PyCharm, we don't want to impose the use of thirs-party plugins 😄

2025-01-21 07:52 UTC, florentLutz requested changes
You have answered pretty much all my comments, thanks ! However, I still think we shouldn't remove those `# noinspection PyUnresolvedReferences` in the api

2025-01-21 15:08 UTC, enricostragiotti commented on src/fastoad/api.py
OK apparently we can solve all of these problems by setting explicitly the variables and methods that are importables by using the __all__ variable
https://discuss.python.org/t/usage-of-all-in-init-py/17936
What do you think?

2025-01-23 10:10 UTC, florentLutz commented on src/fastoad/api.py
Works for me. PyCharm doesn't complain and by the looks of it neither does ruff. I'm resolving the conversation

2025-01-23 10:11 UTC, florentLutz approved these changes
Thaks for the PR and the changes you made for me 😄

2025-01-23 17:48 UTC, merged